server:
    port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: spring-boot-fulfillment-service

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  # Spring JMS Settings
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 1
      max-concurrency: 3
    pub-sub-domain: true
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000

# Logging configuration print only current thread and messages for tutorial purposes
#logging:
#  pattern:
#    console: "[%thread]:%msg%n"
#  level:
#      - ".=info"
#      - "com.memorynotfound=debug"
#      - "org.springframework=info"